// What the door says after a wrong guess. Motivational, allegedly.
export const SECRETS_QUOTES = [
  "wrong, but with such conviction",
  "the door believes in you. the door is also still locked",
  "every great hacker was once a person typing nonsense into a box",
  "not it. but ur posture looked great",
  "rome wasn’t hacked in a day",
  "that was a beautiful guess. incorrect, but beautiful",
  "shoot for the moon. u have landed in my garden",
  "the password is out there. so are pigeons. stay vigilant",
  "u miss 100% of the passwords u don’t guess. u also missed that one",
  "failure is just success wearing a disguise. a very convincing disguise",
  "keep going. the password is not going anywhere. literally",
  "wrong answer, right energy",
  "no. but i felt something",
  "the secret to hacking is believing in yourself and also knowing the password",
  "not quite. hydrate and try again",
  "believe in the version of u that knows the password",
  "u are exactly one correct guess away from being correct",
  "that guess had main character energy. still wrong",
  "a journey of a thousand guesses begins with a wrong one. congrats",
  "the door respects the attempt",
  "incorrect, but the door remembers ur name now",
  "nope. but ur vibes are immaculate",
  "if at first u don’t succeed, that is extremely normal",
  "wrong. the pigeons are taking notes",
  "close. by which i mean not close",
  "every wrong guess is a little poem. that one was free verse",
  "u can do hard things. this is apparently one of them",
  "denied, lovingly",
  "some doors open. some doors build character",
  "the universe heard u. the universe said no",
  "great effort. zero results. very human",
  "u are not locked out of my heart, only my secrets",
  "wrong, but i admire the hustle",
  "the password is patient. so am i. are u?",
  "that was a guess and a half. still one short",
  "think smaller. no, smaller than that",
  "not the password. maybe a good name for a cat though",
  "the door has seen things. that guess was not one of them",
  "u are a shooting star. shooting slightly to the left",
  "manifest harder",
  "wrong. but the sun still rose today and that counts for something",
  "if persistence were the password, u’d be in already",
  "keep guessing. i love watching u grow",
  "nope. stretch ur wrists. this is a marathon",
  "the door says: aw. the door also says: no",
  "incorrect, and yet, so alive",
  "close ur eyes. picture the password. now open them. it wasn’t that",
  "u brought ur whole self to that guess. thank u. no",
  "wrong. the door is proud of u anyway",
  "the password is simple. that guess was complicated. reconsider",
  "u are doing amazing, sweetie. u are also wrong",
  "not it. but ur typing speed is inspiring",
  "the door gives that guess a 10 for confidence",
  "somewhere a pigeon just laughed. don’t take it personally",
  "wrong, but in a way that feels like growth",
  "the secrets remain secret. the effort remains legendary",
  "u tried. the door noticed. the door is still a door",
  "not today. but maybe in like four seconds",
  "the password laughed, but kindly",
  "think of this less as failure and more as data",
  "u are exactly where u need to be: outside",
  "wrong. blink twice if u need a snack",
  "that guess deserved a better password. alas",
  "every no is a yes wearing a little hat",
  "the door admires ur commitment to the bit",
  "denied. the door will remember this fondly",
  "wrong, but the moon is still very pretty tonight",
  "keep ur chin up. the password is at eye level anyway",
  "fun fact: that is not the password",
  "the door heard ‘mm’ in ur heart. it needs to hear it in the box",
  "u have the spirit of a hacker and the password of a stranger",
  "so close to being a completely different guess",
  "wrong. treat yourself to a dekopon and return stronger",
  "nope. but honestly? iconic",
  "that guess was a vibe. the door is not vibes-based",
  "the door believes in second chances. and third. and hundredth",
  "u are the protagonist. this is the montage part",
  "no dice. but plenty of charm",
  "the password saw that guess and went ‘aw’",
  "incorrect. the door has lit a small candle for ur journey",
  "wrong, but the door thinks ur very brave",
  "this door is a teacher. today’s lesson: no",
  "try again. the door is not judging. the door is a little judging",
  "u typed that like u meant it. respect. denied",
  "nope. the door is rooting for u from behind itself",
  "wrong. but ur nose looked great doing it",
  "the door would like to see more of that energy and less of that password",
  "that guess has been added to the door’s memoir",
  "not it. the door suggests a walk and then a better idea",
  "u are one epiphany away. possibly two",
  "wrong. the door is sending u good thoughts and nothing else",
  "close enough for a hug. not close enough for a door",
  "the door thinks u are the type to figure it out. eventually",
  "denied. but the door wants u to know it was a lovely attempt",
  "fear not. the door has never once opened for a coward. or for that",
  "wrong. the door has no idea how u got that but it’s impressed",
  "the password whispered ‘not even warm’ and went back to sleep",
  "u are a rocket. the password is a snail. reconsider ur strategy",
  "nope. but if u squint, that almost looked like trying",
  "the door: still locked. u: still wonderful",
] as const;

export function randomSecretsQuote(previous?: string) {
  let quote: string = SECRETS_QUOTES[0];
  for (let attempt = 0; attempt < 4; attempt += 1) {
    quote = SECRETS_QUOTES[Math.floor(Math.random() * SECRETS_QUOTES.length)];
    if (quote !== previous) break;
  }
  return quote;
}
